apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
  labels:
{{- toYaml .Values.db.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
{{- toYaml .Values.db.labels | nindent 6 }}
  replicas: {{ .Values.db.replicas }}
  template:
    metadata:
      labels:
{{- toYaml .Values.db.labels | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.db.name }}
        image: {{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}
        imagePullPolicy: {{ .Values.db.image.pullPolicy }}
        envFrom:
          - configMapRef:
              name: {{ .Values.db.name }}-configmap
              optional: false
          - secretRef:
              name: {{ .Values.db.name }}-secret
              optional: false
        ports:
        - containerPort: {{ .Values.db.containerPorts.postgres }}
        resources:
{{- toYaml .Values.db.resources | nindent 10 }}
        volumeMounts:
        - name: {{ .Values.db.name }}-volume
          mountPath: /var/lib/postgresql/data       # Path inside container for PostgreSQL
      volumes:
      - name: {{ .Values.db.name }}-volume
        emptyDir: {}     # Use emptyDir instead of hostPath to avoid permission issues
