apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  labels:
{{- toYaml .Values.redis.labels | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.redis.containerPorts.redis }}
    targetPort: {{ .Values.redis.containerPorts.redis }}
    protocol: TCP
    name: redis
  selector:
{{- toYaml .Values.redis.labels | nindent 4 }}
