flask:
  name: flask-app-dev
  labels:
    app: flask-app
    env: dev
    stack: flask-app
  image:
    repository: your-flask-app-image
    tag: dev
    pullPolicy: Always
  replicas: 2
  configmap:
    ## KEY: "value"
    # PostgreSQL Configuration
    POSTGRES_HOST: c0941004-db
    POSTGRES_DB: mydb
    POSTGRES_USER: c0941004
    
    # Redis Configuration
    REDIS_HOST: c0941004-redis
    REDIS_PORT: "6379"
    
    # Flask Configuration
    FLASK_HOST: "0.0.0.0"
    FLASK_PORT: "5000"
    FLASK_ENV: development
    FLASK_DEBUG: "True"
    
    # Application Environment
    APP_ENV: dev
  containerPorts:
      http: 5000
